name: glance
version: ocata
summary: OpenStack Image Service (glance)
description: OpenStack Image Service (glance)
confinement: strict
grade: devel

apps:
  api:
    command: snap-openstack glance-api
    daemon: simple
    plugs:
      - network
      - network-bind
  registry:
    command: snap-openstack glance-registry
    daemon: simple
    plugs:
      - network
      - network-bind
  manage:
    command: snap-openstack glance-manage
    plugs:
      - network

parts:
  glance:
    plugin: python
    python-version: python2
    source: http://tarballs.openstack.org/glance/glance-master.tar.gz
    python-packages:
      - pymysql
      - git+https://github.com/openstack-snaps/snap.openstack#egg=snap.openstack
    constraints: https://raw.githubusercontent.com/openstack/requirements/master/upper-constraints.txt
    build-packages:
      - libffi-dev
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
      - pkg-config
      - gcc
  templates:
    after:
      - glance
    plugin: dump
    source: conf
  # TODO: replace below with scriplets once implemented in snapcraft
  config:
    after:
      - glance
    plugin: dump
    source: http://tarballs.openstack.org/glance/glance-master.tar.gz
    organize:
      etc/*.conf: etc/glance/
      etc/*.ini: etc/glance/
      etc/*.json: etc/glance/
    filesets:
      etc:
        - etc/glance/*.conf
        - etc/glance/*.ini
        - etc/glance/*.json
    stage: [$etc]
    snap: [$etc]
